In [3]:
import numpy as np

In [9]:
a = np.random.randint(0, 10, [3, 3])
b = np.random.randint(0, 10, [1, 3])

In [15]:
a, b

(array([[4, 5, 4],
        [1, 6, 3],
        [9, 4, 0]]),
 array([[3, 7, 2]]))

In [19]:
b @ a.T

array([[55, 51, 55]])

In [17]:
4*3 + 7*1+ 2*9

37